//
// Created by sophia on 9/9/22.
//

#ifndef ILLUMINATIONENGINE_ATTACHMENTOPENGL_HPP
#define ILLUMINATIONENGINE_ATTACHMENTOPENGL_HPP


class AttachmentOpenGL {

};


#endif //ILLUMINATIONENGINE_ATTACHMENTOPENGL_HPP
